url: "https://www.codamos.club/"

timezone: "America/Sao_Paulo"

collections:
  - events

webrick:
  headers:
    Content-Security-Policy: "script-src 'self' https://use.fontawesome.com https://cdn.polyfill.io https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://use.fontawesome.com; img-src 'self' https://licensebuttons.net https://www.google-analytics.com; font-src https://fonts.gstatic.com https://use.fontawesome.com; connect-src https://www.google-analytics.com; media-src 'none' ; object-src 'none' ; frame-src https://www.google.com https://docs.google.com; worker-src 'none' ; frame-ancestors 'none' ; form-action https://api.staticman.net;"
